languageCode = "en"
languageName = "English"
weight = 1

title = "Komal Singh"
copyright = "&copy; 2023 Komal Singh"

[params]
  isoCode = "en"
  displayName = "EN"
  rtl = false

 dateFormat = "2006-01-02"

  mainSections = ["post"]
  description = "A guy with a blog, yikes."

[params.author]
  name = "Komal Singh"
  image = "img/author.jpg"
  headline = "A generally awesome human"
  bio = "A guy with a blog, yikes."
  links = [
  { email = "mailto:hi@kom.al" },
  { mastodon = "https://mas.to/@komal" },
  { x-twitter = "https://x.com/knowkomal" },
  { github = "https://github.com/knowkomal" },
  { link = "https://open.spotify.com/user/31gfgnwm5gaj7oslegei2osn5j5e?si=df1cef4723964785" },
  ]
