# config/_default/menus.en.toml

[[main]]
name              = "Home"
identifier        = "home"
url               = "/"
weight            = 1

[[main]]
name              = "About"
identifier        = "about"
url               = "/about/"
weight            = 2

[[main]]
name              = "Domain Hacks"
identifier        = "domainhacks"
url               = "/domainhacks/"
weight            = 3

[[main]]
name              = "Blog"
identifier        = "blog"
url               = "https://komal.sh/"
weight            = 10

[[main]]
name              = "Subscribe"
identifier        = "subscribe"
url               = "/subscribe/"
weight            = 20
