# config/_default/menus.en.toml

[[main]]
name              = "Home"
identifier        = "home"
url               = "/"
weight            = 1

[[main]]
name              = "About"
url               = "/about/"
weight            = 2

[[main]]
name              = "Blog"
identifier        = "blog"
url               = "/blog/"
weight            = 3

[[main]]
name              = "Domain Hacks"
identifier        = "domainhacks"
url               = "/domainhacks/"
weight            = 4

[[main]]
name              = "Wot I Read"
url               = "/wir/"
weight            = 5

[[main]]
name              = "Subscribe"
identifier        = "subscribe"
url               = "/subscribe/"
weight            = 6

[[footer]]
name              = "Categories"
identifier        = "categories"
url               = "/categories/"
weight            = 21

[[footer]]
name              = "Tags"
identifier        = "tags"
url               = "/tags/"
weight            = 20

[[footer]]
name              = "DomainBoi"
identifier        = "DomainBoi"
url               = "https://boi.domains/"
weight            = 22

[[footer]]
name              = "Report Lost Item"
identifier        = "lostitem"
url               = "https://lost.kom.al"
weight            = 23

[[footer]]
name              = "Want This Domain?"
identifier        = "wantthisdomain"
url               = "/btd/"
weight            = 24

[[footer]]
name              = ""
identifier        = "privacy"
url               = "/privacy/"
weight            = 25