# config/_default/menus.en.toml

[[main]]
name              = "Home"
identifier        = "home"
url               = "/"
weight            = 1

[[main]]
name              = "About"
identifier        = "about"
url               = "/about/"
weight            = 2

[[main]]
name              = "Domain Hacks"
identifier        = "domainhacks"
url               = "/domainhacks/"
weight            = 4

[[main]]
name              = "Blog"
identifier        = "blog"
url               = "/blog/"
weight            = 3

[[main]]
name              = "Subscribe"
identifier        = "subscribe"
url               = "/subscribe/"
weight            = 5

[[footer]]
name              = ""
identifier        = "privacy"
url               = "/privacy/"
weight            = 6


[[footer]]
name              = "DomainBoi"
identifier        = "DomainBoi"
url               = "https://boi.domains/"
weight            = 7